In [7]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

In [8]:
dataset = [
    ["Milk","Bread","Butter"],
    ["Milk","Diaper","Juice","Bread"],
    ["Milk","Diaper","Bread"],
    ["Diaper","Juice","Bread"],
    ["Milk","Diaper","Juice","Bread"]
]

In [9]:
# Extract all items
all_items = set()
for transaction in dataset:
    for item in transaction:
        if item not in all_items:
            all_items.add(item)
print("All Items ", all_items)

All Items  {'Juice', 'Butter', 'Diaper', 'Milk', 'Bread'}

In [9]:
transaction_list = []

for transaction in dataset:
    transaction_dict={}

    for item in all_items:
        transaction_dict[item] = item in transaction
    transaction_list.append(transaction_dict)

print(transaction_list)
df = pd.DataFrame(transaction_list)

[{'Butter': True, 'Diaper': False, 'Juice': False, 'Bread': True, 'Milk': True}, {'Butter': False, 'Diaper': True, 'Juice': True, 'Bread': True, 'Milk': True}, {'Butter': False, 'Diaper': True, 'Juice': False, 'Bread': True, 'Milk': True}, {'Butter': False, 'Diaper': True, 'Juice': True, 'Bread': True, 'Milk': False}, {'Butter': False, 'Diaper': True, 'Juice': True, 'Bread': True, 'Milk': True}]

In [8]:
df

   Butter  Diaper  Juice  Bread   Milk
0    True   False  False   True   True
1   False    True   True   True   True
2   False    True  False   True   True
3   False    True   True   True  False
4   False    True   True   True   True

In [11]:
frequent_itemsets = apriori(df, min_support = 0.6, use_colnames = True)
print("Frequent Itemset:")
frequent_itemsets

Frequent Itemset:

    support                           itemsets
0       0.8                frozenset({Diaper})
1       0.6                 frozenset({Juice})
2       1.0                 frozenset({Bread})
3       0.8                  frozenset({Milk})
4       0.6         frozenset({Diaper, Juice})
5       0.8         frozenset({Diaper, Bread})
6       0.6          frozenset({Diaper, Milk})
7       0.6          frozenset({Bread, Juice})
8       0.8           frozenset({Bread, Milk})
9       0.6  frozenset({Diaper, Bread, Juice})
10      0.6   frozenset({Diaper, Bread, Milk})

In [14]:
# rules = association_rules(frequent_itemsets, metric="confidence",min_threshold=0.7, num_itemsets = 2)
rules = association_rules(
    frequent_itemsets,
    metric="confidence",
    min_threshold=0.7
)
print("Association Rules:")
rules

Association Rules:

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({Diaper}),frozenset({Juice}),0.8,0.6,0.6,0.75,1.2500,1.0,0.12,1.6,1.00,0.75,0.375,0.875
1,frozenset({Juice}),frozenset({Diaper}),0.6,0.8,0.6,1.00,1.2500,1.0,0.12,inf,0.50,0.75,1.000,0.875
2,frozenset({Diaper}),frozenset({Bread}),0.8,1.0,0.8,1.00,1.0000,1.0,0.00,inf,0.00,0.80,0.000,0.900
3,frozenset({Bread}),frozenset({Diaper}),1.0,0.8,0.8,0.80,1.0000,1.0,0.00,1.0,0.00,0.80,0.000,0.900
4,frozenset({Diaper}),frozenset({Milk}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
5,frozenset({Milk}),frozenset({Diaper}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
6,frozenset({Juice}),frozenset({Bread}),0.6,1.0,0.6,1.00,1.0000,1.0,0.00,inf,0.00,0.60,0.000,0.800
7,frozenset({Bread}),frozenset({Milk}),1.0,0.8,0.8,0.80,1.0000,1.0,0.00,1.0,0.00,0.80,0.000,0.900
8,frozenset({Milk}),frozenset({Bread}),0.8,1.0,0.8,1.00,1.0000,1.0,0.00,inf,0.00,0.80,0.000,0.900
9,"frozenset({Diaper, Bread})",frozenset({Juice}),0.8,0.6,0.6,0.75,1.2500,1.0,0.12,1.6,1.00,0.75,0.375,0.875
10,"frozenset({Diaper, Juice})",frozenset({Bread}),0.6,1.0,0.6,1.00,1.0000,1.0,0.00,inf,0.00,0.60,0.000,0.800
11,"frozenset({Bread, Juice})",frozenset({Diaper}),0.6,0.8,0.6,1.00,1.2500,1.0,0.12,inf,0.50,0.75,1.000,0.875
12,frozenset({Diaper}),"frozenset({Bread, Juice})",0.8,0.6,0.6,0.75,1.2500,1.0,0.12,1.6,1.00,0.75,0.375,0.875
13,frozenset({Juice}),"frozenset({Diaper, Bread})",0.6,0.8,0.6,1.00,1.2500,1.0,0.12,inf,0.50,0.75,1.000,0.875
14,"frozenset({Diaper, Bread})",frozenset({Milk}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
15,"frozenset({Diaper, Milk})",frozenset({Bread}),0.6,1.0,0.6,1.00,1.0000,1.0,0.00,inf,0.00,0.60,0.000,0.800
16,"frozenset({Bread, Milk})",frozenset({Diaper}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
17,frozenset({Diaper}),"frozenset({Bread, Milk})",0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
18,frozenset({Milk}),"frozenset({Diaper, Bread})",0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750

In [15]:
strong_rules = rules[(rules['confidence']>0.7) & (rules['lift']>1) ]
print("Strong Association rules (confidence > 0.7 and Lift>1): ")
strong_rules.head()

Strong Association rules (confidence > 0.7 and Lift>1):

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({Diaper}),frozenset({Juice}),0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875
1,frozenset({Juice}),frozenset({Diaper}),0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875
9,"frozenset({Diaper, Bread})",frozenset({Juice}),0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875
11,"frozenset({Bread, Juice})",frozenset({Diaper}),0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875
12,frozenset({Diaper}),"frozenset({Bread, Juice})",0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875